### ISSUE TITLE
Add information how to use the tool in a Readme 

### ISSUE THREAD

**Issue by LAfricain** [tiagoporsch/humanfx#1]
I would like to use this tool with a M17R3 alienware with the same specs. Can you help?

**Comment by tiagoporsch** [comment]
If you build the program and run it, it shows some usage information. For example, you can run `humanfx static FFFF00` to change you keyboard to a static yellow, given that the controller on your M17R3 is exactly the one I developed for in this project.

**Comment by LAfricain** [comment]
I clone the repo then:
```
make
gcc -Wall -Wextra -o humanfx humanfx.c main.c -lusb-1.0
cyrille@alienware-m17-r3:~/Documents/github/humanfx$ make install 
mkdir --parents "/home/cyrille/.local/bin"
cp "humanfx" "/home/cyrille/.local/bin"
cyrille@alienware-m17-r3:~/Documents/github/humanfx$ humanfx static FFFF00```

But nothing happens, if I use openRGB only the left part of  the keyboard switch on.

**Comment by tiagoporsch** [comment]
This "driver" only really supports the Dell G15 laptop (and one specific version).
If you want to make this work with other similar laptops that use similar controllers for the keyboard backlight, you will need to make some adjustments.
You said that when you use OpenRGB the left part of your keyboard gets correctly lit up. This seems to me like you need to change the selected zones when sending a command. Try sending the commands to zones 4, 5, 6, and so on until some number works for the rest of your keyboard.

**Comment by LAfricain** [comment]
> If you want to make this work with other similar laptops that use similar controllers for the keyboard backlight, you will need to make some adjustments.

OK what kind of adjustements?

> This seems to me like you need to change the selected zones when sending a command. Try sending the commands to zones 4, 5, 6, and so on until some number works for the rest of your keyboard.

On OpenRGB? I have only unknown LED, for LED and for zone I have Unknow and it's not working when I try to select only one.

**Comment by tiagoporsch** [comment]
> OK what kind of adjustements?

That would depend on your specific hardware. You could try running your Alienware program and capturing the USB packets, and then reverse engineer the protocol. That's how I first developed this utility.

> On OpenRGB?

No, on this utility. See the function `example_static` on `main.c`: I pass a macro `ZONE_ALL` to the `send_zone_select` function. The macro expands to the four zones I have on my keyboard (0x00, 0x01, 0x02 and 0x03). Maybe your keyboard has different zone numbers, so you could try sending this command to zones 0x04, 0x05, 0x06, and so on until you find some zone ID that corresponds to your keyboard and it lights up.

**Comment by LAfricain** [comment]
thank you for your help, but I have no coding skill... Even If I'm very interresting about it.

**Comment by tiagoporsch** [comment]
No problem, good luck on your programming journey!
