### ISSUE TITLE
Almost works (alien logo colours change, but not keyboard)...

### ISSUE THREAD

**Issue by ici-chacal** [tiagoporsch/humanfx#2]
I have built this neat little utility on my Alienware m15R2, and using the 'static' option I can change the colours of the alien head power button, the alien head on the lid, and the 'Tron' light bar on the back of the machine. But alas, the keyboard remains unaffected...

It's a per-key RGB keyboard (Darfon Electronics Corp - 0d62:0a1c), and the code talks of left middle and right 'zones', but not sure if this matters or not.

Does anyone know how to get this tool to change the key colours..?

**Comment by tiagoporsch** [comment]
Hello!

I think that you will need a different driver, specifically for your keyboard controller (0d62:0a1c).

You could try sending commands to different zones (0x05, 0x06), but I don't think this driver (and even the 187c:0550 device) handles per-key colors.

**Comment by ici-chacal** [comment]
Yeah, those extra zone numbers didn't work. I did, however, find this other tool:
https://github.com/T-Troll/alienfx-tools

It's a Windows program, but it can change the key colours on my keyboard, so somewhere in here is some code that can perhaps be ported into your app...

**Comment by tiagoporsch** [comment]
I took a look at the project you linked, and it seems to use a completely different protocol. It is out of scope of this project, but if you want to try, feel free to fork this repository!
